#!/bin/bash

curl -X POST --data \
	"grant_type=client_credentials&client_id=$WHERE_UID&client_secret=$WHERE_SECRET" \
	https://api.intra.42.fr/oauth/token >.token.json

# curl -s -H "Authorization: Bearer ";
# 	curlCmd_.push_back(URL_ + "v2/users/" + login);
