#!/bin/bash

set -eo pipefail

if [ $# -eq 0 ];then 
	echo "Usage: $0 <login>"
	exit 1
fi

login="$1"
abspath="/home/cdomet-d/workflow-utils/scripts/where-script"
echo "Seeking user \"$login\"..."

declare -i expiration

if [ -f "$abspath"/bestbefore.json ]; then
	expiration=$(jq -r '.expire' "$abspath"/bestbefore.json)
	now=$(date +%s)
else
	expiration=0
fi

if [ "$now" -ge "$expiration" ]; then
	if ! curl -s -X POST --data \
		"grant_type=client_credentials&client_id=$WHERE_UID&client_secret=$WHERE_SECRET" \
		https://api.intra.42.fr/oauth/token >"$abspath"/token.json; then
		echo "Error: failed to obtain access token"
		exit 1
	fi
	expire_in=$(jq -e -r '.expires_in' "$abspath"/token.json)
	bestbefore=$(($(date +%s) + "$expire_in"))
	jq -n --argjson exp "$bestbefore" \ '{expire_in: $exp}' >"$abspath"/bestbefore.json
fi

token=$(jq -r '.access_token' "$abspath"/token.json)
curl -s -H "Authorization: Bearer $token" https://api.intra.42.fr/v2/users/"$login" >"$abspath"/user.json

if jq -e -r '.location' "$abspath"/user.json >/dev/null; then
	jq -r '.location' "$abspath"/user.json
else
	echo "Error: no location found for \"$login\""
fi

rm "$abspath"/user.json
