#!/bin/bash

make fclean
if [ "$1" = "-n" ]; then
	norminette > norm
	grep -v "OK" norm
	rm norm
fi

# The following lines serve to remove work files and directories 
# You can update them to tailor your needs

# if [ -f "out" ]; then
# 	rm out
# fi
# if [ -f "*.log" ]; then
# 	rm *.log
# fi

# if [ -d "scripts/output" ]; then
# 	rm -r scripts/output
# fi
