#!/bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: $0 <login>"
	exit 1
fi

login="$1"
abspath="/home/cdomet-d/workflow-utils/scripts/tutor-tracking"

declare -i expiration

if [ -f "$abspath"/bestbefore.json ]; then
	expiration=$(jq -r '.expire' "$abspath"/bestbefore.json)
	now=$(date +%s)
else
	expiration=0
fi

if [ "$now" -ge "$expiration" ]; then
	if ! curl -s -X POST --data \
		"grant_type=client_credentials&client_id=$WHERE_UID&client_secret=$WHERE_SECRET" \
		https://api.intra.42.fr/oauth/token >"$abspath"/token.json; then
		echo "Error: failed to obtain access token"
		exit 1
	fi
	expire_in=$(jq -e -r '.expires_in' "$abspath"/token.json)
	bestbefore=$(($(date +%s) + "$expire_in"))
	jq -n --argjson exp "$bestbefore" \ '{expire_in: $exp}' >"$abspath"/bestbefore.json
fi

token=$(jq -r '.access_token' "$abspath"/token.json)
curl -s -H "Authorization: Bearer $token" https://api.intra.42.fr/v2/users/"$login" \
	>"$abspath"/user.json

if jq -e -r '.login' "$abspath"/user.json >/dev/null; then
	echo -n "Informations for: "
	jq -r '.login' "$abspath"/user.json
else
	echo "Error: no such login"
	exit 1
fi

echo -n "Level: "
if jq -e -r '.cursus_users[] | select(.grade == "Cadet") | .level' "$abspath"/user.json>/dev/null; then
	jq '.cursus_users[] | select(.grade == "Cadet") | .level' "$abspath"/user.json
else
	jq '.cursus_users[] | select(.grade == "Transcender") | .level' "$abspath"/user.json
fi

echo "Current projects: "
jq -r '.projects_users[] | select(.final_mark == null) | "\(.project.name)\t\(.created_at)"' \
	"$abspath"/user.json |
	while IFS=$'\t' read -r project_name created_at; do
		now=$(date +%s)
		created_epoch=$(date -d "$created_at" +%s)
		seconds_elapsed=$((now - created_epoch))
		days=$((seconds_elapsed / 86400))

		printf '%-15.15s | Since: %d days\n' \
			"$project_name" "$days"
	done

echo -n "Alone in the Dark grade: "
jq '.projects_users[] | select(.project.name == "Alone in the Dark") | .final_mark' \
	"$abspath"/user.json || echo "Alone in the Dark not found"

rm "$abspath"/user.json >/dev/null 2>&1
